# Generated by Django 4.0.5 on 2022-07-02 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimepredictionlog',
            name='date',
        ),
        migrations.AddField(
            model_name='crimepredictionlog',
            name='Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimepredictionlog',
            name='DayOfWeek',
            field=models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], default='MONDAY', max_length=1000),
        ),
        migrations.AddField(
            model_name='crimepredictionlog',
            name='Latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crimepredictionlog',
            name='Longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crimepredictionlog',
            name='PdDistrict',
            field=models.CharField(choices=[('RI', 'RICHMOND'), ('NO', 'NORTHERN'), ('CE', 'CENTRAL'), ('TE', 'TENDERLOIN'), ('SO', 'SOUTHERN'), ('BA', 'BAYVIEW'), ('IN', 'INGLESIDE'), ('MI', 'MISSION'), ('PA', 'PARK'), ('TA', 'TARAVAL')], default='SOUTHERN', max_length=1000),
        ),
    ]
